# Generated by Django 3.0.7 on 2020-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(blank=True, max_length=50)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('Address', models.TextField(max_length=100)),
                ('DOB', models.DateField()),
                ('job', models.ManyToManyField(blank=True, to='employees.AvailableJobs')),
            ],
        ),
    ]
