# Generated by Django 3.0.7 on 2020-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
